### ISSUE TITLE
Getting a standard *.1 file requires installing Ronn

### ISSUE THREAD

**Issue by ericpruitt** [discoteq/flock#22]
I think a precompiled *.1 file should be included with the project so people don't have to install Ronn to get a man page. I'd submit a pull request adding this, but I don't have Ronn installed to generate it.

**Comment by josephholsten** [comment]
Seems reasonable. Also, I’ve switched to using pandoc for text to roff conversions in the rest of my life.

If we do this, we should have a test that verifies the pregenerated roff file matches what is generated by a clean build.

**Comment by ericpruitt** [comment]
Are *you* going to do this?
