### ISSUE TITLE
flock: failed to execute command - No such file or directory

### ISSUE THREAD

**Issue by diego-vieira** [discoteq/flock#26]
I have just tried to use it on macOS Mojave but can't.

```
flock -n ~/my-lock.lock -c "rsync -avEr --progress --delete-after -e \"ssh -p 5443 -o StrictHostKeyChecking=no\" ~/Documents user@192.168.1.32:/Documents/"
```

The command above says
```
flock: failed to execute command: -c: No such file or directory
```

Then tried without `-c` and got `No such file or directory` as well.

Any ideas?

Thanks

**Comment by yaoxiaohang** [comment]
flock -n ~/my-lock.lock rsync -avEr --progress --delete-after -e \"ssh -p 5443 -o StrictHostKeyChecking=no\" ~/Documents user@192.168.1.32:/Documents/

**Comment by josephholsten** [comment]
Thanks @yxh, that’s about what I was going to suggest.

@diego-vieira: if this updated command works for you, could you suggest how we might improve the docs to be more clear?

**Comment by josephholsten** [comment]
And actually, it sounds like you also would like #23, which I’ve been avoiding because I hoped it was unnecessary. I’d love your opinion.

**Comment by diego-vieira** [comment]
@yaoxiaohang thanks, just tested and it works just fine.

@josephholsten just added another example to README on
https://github.com/discoteq/flock/pull/27

Many thanks

**Comment by ruchikasharma09** [comment]
Hi,

I am trying to build the project on MAC OS Mojave and still getting this error:

flock: failed to execute command: -c: No such file or directory
make: *** [/Users/.../.gradle/caches/golang/go1.14.1.darwin-amd64.tar.gz] Error 66.

Could you please help me to resolve this.

**Comment by josephholsten** [comment]
@ruchikasharma09 can you paste the exact command you ran? I'm having a hard time understanding how either gradle or golang could be involved in a build of this project.
