### ISSUE TITLE
tag release?

### ISSUE THREAD

**Issue by zx2c4** [discoteq/flock#29]
No release in 5 years, yet there have been changes that are useful (such as `-x`).

Could you tag a release please?

**Comment by josephholsten** [comment]
@zx2c4 why yes, I’d be happy to give you commit privileges!

**Comment by zx2c4** [comment]
Not sure I'm up for maintaining this, but thanks for the offer. I was just thinking a simple `git tag ... && git push --tags` would do the trick here.

**Comment by josephholsten** [comment]
Oh, you’re *that* random series of characters. Ok, fine. You’ve got more important projects to maintain!

**Comment by josephholsten** [comment]
https://github.com/discoteq/flock/releases/tag/v0.3.0

**Comment by zx2c4** [comment]
Sweet! Thanks a lot. Very appreciated.
